name: Docker Image CI

on:
  workflow_dispatch:  # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    #- name: Build the Docker image
    #  run: docker build . --file docker/Dockerfile --tag migpt-cli:$(date +%s)

    - name: Login to ghcr.io
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}  # 自动获取当前GitHub用户名
        password: ${{ secrets.GHCR_TOKEN }}  # 引用之前设置的Secrets

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build & push image to ghcr
      uses: docker/build-push-action@v5
      with:
        context: .  # Docker构建上下文（项目根目录）
        file: docker/Dockerfile
        push: true  # 开启推送
        tags: |
        tags: |
          ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}:${{ github.sha }}
          ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max